### ISSUE TITLE
Update footer layout

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#137]
From Jenna https://www.dropbox.com/sh/3ok9zru1eos7mn1/AACScnmemlWZEX6Vdyz8au5Na?dl=0

**Comment by bree-z** [comment]
This looks mostly good, but I have a few questions:

1. Link styling is: no text decoration and underlined on hover, but should it be the opposite, so that it's underlined, with no underline on hover?  (See, for example, the last two sentences in the left section of the header: "Hoc est non dividere, sed frangere. Duo Reges: constructio interrete.")

2. The image looks very large in the preview, even though it's the correct size when published.  I'm not sure if this is a big deal or is something we can change.  

<img width="1269" alt="footerpreview" src="https://user-images.githubusercontent.com/7189824/40654785-f357eefe-6347-11e8-9c60-a7fc2f12ccc3.png">

Thanks!

**Comment by bree-z** [comment]
Thanks, Boone!  Link styling change looks good to me!  I'll assume it's OK to close this one, but please reopen if you disagree, thanks!  :)
