### ISSUE TITLE
Lorem ipsum still exists

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/openlab-theme#209]
From @charliemedwards 

Lorem ipsum on Brand Settings and Communication Settings.

Possible that some of the below hasn't been implemented: See https://docs.google.com/document/d/1Sr7E3fL81bq8X7Ji43NXWbBbGbLLLGtR_sIz6sUf0qk/edit#heading=h.gap7lnmo9gk5 I'll have to review to see if it's on me or Sam.

**Comment by samradd** [comment]
I took a pass at these, @boonebgorges (text also added to the Replacement Text doc). Please feel free to make clarifying edits, especially to the invitations tab since it's describing a plugin you created. Thanks!

**Email**
Intro text: Members of your community can be sent various notifications via email. Manage all settings related to emails here.
Email Appearance: Customize the visual design of emails that will be sent to community members.
Email Templates: Manage the content that’s included in emails that automatically are sent out to members based on triggers (e.g. A welcome email is sent to new members of a group).
Group Email Options: Update settings related to Daily Digests & weekly Summaries of group activities in your community, toggle global unsubscribe links, modify group admin abilities related to email subscription settings, and establish spam prevention guidelines.
 
**Invitations**
Intro Text: Invite Anyone allows community members to invite non-members to your community and its groups via email. 
Invite Anyone: Manage the invite email content template, control which members-types are able to send various kinds of invitations, control address book integration, view sent invitations and related statistics.

**Comment by boonebgorges** [comment]
Thanks, @samradd ! I've made just a few small changes for readability. Bree, please have a look, and let me know if you have suggestions for any additional mods to the text.

**Comment by bree-z** [comment]
This looks good to me, except for one small question about the text in the Invitations tab:

"Manage the invite email content template, control which **members-types** are able to send various kinds of invitations, control address book integration, view sent invitations and related statistics."

Should "members-types" be "member-types"?  

Thanks!

**Comment by boonebgorges** [comment]
Elsewhere, we use 'Member Types' (capitalized, no hyphen) or 'member types' (lowercase, no hyphen). We don't use the hyphen anywhere.

**Comment by jennaspevack** [comment]
I think we should use use member types (no hyphen).

**Comment by boonebgorges** [comment]
Thanks, @jennaspevack. I've made the change.

**Comment by bree-z** [comment]
Looks good, thanks!
