### ISSUE TITLE
Braille toggle for private messages overlaps with star icon

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/openlab-theme#235]
Hi Boone, 

Braille looks good, except for one small thing - the enable/disable Braille toggle for message replies overlaps with the star icon used to star messages.  

![braillestariconoverlap](https://user-images.githubusercontent.com/7189824/40545063-17c6859c-6033-11e8-81a5-281008ecad1a.png)

**Comment by boonebgorges** [comment]
Thanks, @bree-z ! I hadn't spotted this, since the star only shows up on a new reply that's posted via AJAX. This is because the openlab-theme was written before the Star functionality was added to BP. I'll open a separate ticket to discuss it. In the meantime, I've put a styling fix in place that prevents overlap.

**Comment by bree-z** [comment]
Looks good, thanks Boone!
