### ISSUE TITLE
Mobile > Group directories:  'See more' link doesn't appear when group description is truncated

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/openlab-theme#258]
On mobile, the 'See More' link that should appear after a truncated group description doesn't appear on group directories.

### CBOX-OL Mobile

![groupdirectory_cbox-olmobile](https://user-images.githubusercontent.com/7189824/43209292-f4b74154-9034-11e8-8903-53076be67090.png)

### OpenLab Mobile

![groupdirectory_olmobile](https://user-images.githubusercontent.com/7189824/43209220-c87447b8-9034-11e8-868e-1ff36354cef8.png)

### CBOX-OL Desktop

<img width="1060" alt="groupdirectory_cbox-oldesktop" src="https://user-images.githubusercontent.com/7189824/43209388-227f7ca0-9035-11e8-8712-07ad9ec508d0.png">

**Comment by boonebgorges** [comment]
It appears that the truncation script was being run twice, which was causing the link to be added and then removed. I've removed the duplicate.

There's another issue with mobile browsers having to do with the 'resize' event. It gets fired too often (such as on browser chrome resize), which means that our truncation scripts are overfired. I've put some logic in place that ought to prevent it.

I think the issue is fixed, but it's not easy to verify because it's hard to reproduce in the first place.

**Comment by bree-z** [comment]
Thanks, Boone!  Truncation appears to be working as expected.  I'm not sure if that means we can close this, but it looks good to me so far.

**Comment by boonebgorges** [comment]
Thank you!
