### ISSUE TITLE
Clickink My Friends in Profile generates unexpected page

### ISSUE THREAD

**Issue by sreal19** [cuny-academic-commons/openlab-theme#262]
Clicking My Friends in my profile loads this page. I don't think My Portfolio belongs here. Does it? You don't get this on the desktop.
![image](https://user-images.githubusercontent.com/8832300/43220123-3ba2dd12-9017-11e8-8901-4e52de5e1915.png)

**Comment by boonebgorges** [comment]
'My Portfolio' corresponds to 'My Profile' on desktop.

This is working as per the design, so I'm passing it over to @jennaspevack for consideration.

**Comment by jennaspevack** [comment]
Yes, this is the mobile view of MOL/Profile and is working per the OpenLab design. The reason the subheading is changed is because the flow has changed in the mobile view. It didn't make sense to have the sidebar subheading "My Profile" below the content so we changed it to refer to the corresponding Portfolio link.

**Comment by boonebgorges** [comment]
Thanks, @jennaspevack !
