### ISSUE TITLE
Admin: Group Type order doesn't take on the front end

### ISSUE THREAD

**Issue by agmckinney** [cuny-academic-commons/openlab-theme#264]
When attempting to change the order of the group types, the changes take on the back end but not on the front end.

On the back end, Projects were #4 and Portfolios were #2 but I changed Projects to #2 and Portfolios to #4 
![screen shot 2018-07-27 at 10 48 40 am](https://user-images.githubusercontent.com/11300891/43327920-bd35c8ac-918a-11e8-99b7-ba744fe0e0d0.png)

But on the front end, Portfolios remained #2 and Projects remained #4 both in the top level menu and the front page group directories
![screen shot 2018-07-27 at 10 50 30 am](https://user-images.githubusercontent.com/11300891/43328020-f75a3158-918a-11e8-9c9a-9af2660a2ba9.png)

**Comment by boonebgorges** [comment]
Thanks for the report. The "order" field in these boxes only affects the order in which the items appear in dropdowns throughout the site. Nav menus and front-page widgets are separately editable by the administrator, and thus are not changed automatically.

I'll tentatively place this in the Some Day milestone with a needs-design tag, but I'm going to suggest that we don't add the feature, because it'd make it impossible for the navigation/front-end widget order to differ from dropdown order, a diversion which might be desirable for some use cases.

**Comment by agmckinney** [comment]
Got it. Thanks, Boone!

**Comment by boonebgorges** [comment]
Closing based on the above reasoning. This kind of change is unusual enough that a manual change in the nav item is not a big ask. And there are use cases where one might reasonably want the nav order to be different from the "type" order as displayed in dropdowns.
