### ISSUE TITLE
Change Heading for Site-wide Calendar

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/openlab-theme#272]
The heading for the site-wide calendar is 'OpenLab Calendar': http://openlabdev.commonsinabox.org/calendar/ 

Could we delete 'OpenLab' so it's just 'Calendar'?  

And I couldn't find anywhere in the Dashboard to modify this, so apologies if I'm missing something. 

Thanks!

![screen shot 2018-08-16 at 2 34 31 pm](https://user-images.githubusercontent.com/7189824/44228386-2fc3de80-a163-11e8-85de-5dab97550dd1.png)

**Comment by boonebgorges** [comment]
These pages are created automatically at installation. I've changed the logic of the routine that creates them so that they're just called 'Calendar'. I've also made a manual change to the pages at http://openlabdev.commonsinabox.org/wp-admin/edit.php?post_type=page so that they are called Calendar. Since we don't have an environment for testing installation, I'm going to mark resolved.
