### ISSUE TITLE
Courses Directory: 'Term' filter dropdown doesn't have a default value

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/openlab-theme#273]
Hi Boone, 

I'm not sure if this is just an artifact of too much messing around on the dev site, but the 'Term' dropdown on the Courses directory is a little wonky:

1. The default value should be 'Term', but it's blank.  
2. And the dropdown has a strange blank value between 'All' and 'asdf'.  

Thanks!

![coursedirectory_termfilter](https://user-images.githubusercontent.com/7189824/44228299-fab78c00-a162-11e8-8e0f-3366ccfec4bf.png)

![coursedirectory_termfilter2](https://user-images.githubusercontent.com/7189824/44228300-fab78c00-a162-11e8-8e0a-72d90d4b8a10.png)

**Comment by boonebgorges** [comment]
> I'm not sure if this is just an artifact of too much messing around on the dev site,

It is, but the messing around uncovered a potential bug. The Term dropdown is populated by actual values of Term in the database. In this case, at least one course had an empty Term, which was putting an empty item in the Term dropdown. And because this new null Term had a null value, it was being selected instead of `Term`, which is *supposed* to be the null value.

I've put logic in place to eliminate empty values of Term, so this should not happen anymore.
