### ISSUE TITLE
BuddyPress: Support "Settings > Export Data" page

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/openlab-theme#284]
BuddyPress 4.0.0 introduced a "Settings > Export Data" page to match the GDPR functionality introduced in WordPress 4.9.6.

This page resides at `/members/me/settings/data/`, but since `openlab-theme` has a custom WP admin bar and subnav, this page isn't really visible.

The page usually looks like this on a default BuddyPress install:
https://buddypress.org/wp-content/uploads/1/2018/11/data-export.png

If you navigate to that URL in `openlab-theme`, the main content block is blank.

There are two things that need to be done:
- [x] Add support for the `/members/me/settings/data/` page (see commit 885daf7)
- [x] Amend the breadcrumb when on a "My Settings" page to add a link to "Export Data" (see commit e6a559e)

I have most of this ready to commit.  I just need the go-ahead from somebody.  It might be that we don't want to surface this functionality in `openlab-theme` for CBOX 1.1.1, if at all.

CC @boonebgorges

**Comment by boonebgorges** [comment]
Thumbs up from me. Thanks, @r-a-y !

**Comment by r-a-y** [comment]
@boonebgorges - I've implemented the Export Data page.

In commit 885daf7, I decided not introduce another template override, but wanted to inherit the template part from the BuddyPress side.  One thing I had to do was hide the `<h2>` heading since we use a custom header style and `<h2>` would have duplicated the header text twice.  Let me know what you think.

**Comment by boonebgorges** [comment]
Good call. This seems like a reasonable compromise.

**Comment by bree-z** [comment]
Hi @r-a-y and @boonebgorges , 

Just wanted to check whether this is going in 1.1.1, and if so does it need any testing?

Thanks!

**Comment by boonebgorges** [comment]
Yes, I think it should - @r-a-y could you please deploy it to openlabdev.commonsinabox.org so that @bree-z can have a look?

**Comment by r-a-y** [comment]
@bree-z - Change is deployed on the dev site.

To test, navigate to `/members/me/settings/data/` to view the new page.  If you click on "Request personal data export", the site admin should receive an email to review the request,

Once this happens, the workflow for the site admin is as follows:
- Once logged in as the site admin, in the WP admin dashboard, navigate to "Tools > Export Personal Data".
- When on this page, the admin can review all the requests for data exports and approve them.  If you approve the request, the user will get an email with a link to download their data export.  The user can also visit their "Settings > Data" page and the download link will be available there as well.

More info about the WP admin dashboard's "Tools > Export Personal Data" page can be found here:
https://codex.wordpress.org/Tools_Export_Personal_Data_Screen

Do we need to add documentation about this somewhere?

**Comment by bree-z** [comment]
Thanks, Ray and Boone!  This is working well — I'm able to request the export, approve it as an admin, and receive the email and download the data.  I do have a few questions:

- A small thing, but after requesting user data, there’s a message that is a little strange, saying "You previously requested an export of your personal data on February 13, 2019. You will receive a link to download your export via email once we are able to fulfill your request."  I'm assuming this awkward phrasing of the first sentence is just because this is my first request and thus there’s no previous request date to reference?  I'd have to test tomorrow to be sure.  But, if there's no previous request, it might make more sense to have a different message, something like "Thank you for your request.  You will receive a link..." 

- Also, I'm wondering whether you want to take a look at the change in the subnav interface, @jennaspevack ?  The extra link in the subnav does make things look a little crowded with the "Delete Account" link and the "Active x time ago."  Perhaps we might want to consider putting the export data button on the Account Settings page (e.g. https://openlabdev.commonsinabox.org/members/testfaculty/settings/), and taking it out of the subnav?  

And, yes, I think we do need to add this to documentation.  

Thanks!

<img width="1192" alt="exportdata" src="https://user-images.githubusercontent.com/7189824/52734661-cb5bcd80-2f93-11e9-8276-3e5f3f69295f.png">

**Comment by boonebgorges** [comment]
Thanks for having a look, @bree-z 

The message is from BuddyPress and is not, at the moment, easily changeable. Let's look at that for a future release.

I don't have a personal objection to changing the location of the Delete Account link, but I should note that if we do move it, it'll mean bumping this ticket from the 1.1.1 milestone - it's a departure from the way that BP works that will require some custom work that's out of scope for a maintenance release. (The main reasons for including the ticket in 1.1.1 in the first place were (a) for improved GDPR compliance and (b) because visiting the URL currently gives a blank screen, which seems buggy, but I don't think either of these is critical enough to hold up the release.)

**Comment by bree-z** [comment]
Thanks, @boonebgorges 

That all makes sense to me -- it seems better to include in 1.1.1 . 

Just wondering whether @charliemedwards or @jennaspevack should make the final decision about scope?

**Comment by boonebgorges** [comment]
Looks like we're going with this for 1.1.1.
