### ISSUE TITLE
Consider replicating CBOX-OL setup landing page to CBOX classic

### ISSUE THREAD

**Issue by mkgold** [cuny-academic-commons/openlab-theme#50]
per our conversation today on the CBOX-OL dev call, I'd love for us to think about whether we can port the newly designed elements of CBOX-OL landing page that one sees on the dashboard after setup.

I'm creating this ticket here, because I would like to develop it as part of the CBOX-OL grant, but Boone, we can move this ticket to the CBOX github if that would be better, and as long as we won't lose track of it there.

**Comment by boonebgorges** [comment]
@r-a-y Can you give an update on feasibility for this? Will it be easy to migrate Classic content over? Eg, the theme metabox.

**Comment by r-a-y** [comment]
Classic already uses the styling of OpenLab, but doesn't have the exact same content.

Here's a screenshot of the dashboard with Classic in the latest development build:
![2018-05-21_105523](https://user-images.githubusercontent.com/505921/40321919-2839f636-5d20-11e8-802b-85f5afb326a1.png)

OpenLab mostly differs because it has more things to configure.  If you want me to change up the content for Classic, let me know with what.

**Comment by boonebgorges** [comment]
This seems good enough for me. If there are specific items to merge back, we can do it separately.
