### ISSUE TITLE
About Page: Contact Us Link Missing

### ISSUE THREAD

**Issue by sreal19** [cuny-academic-commons/openlab-theme#74]
There is no Contact Us Link on the About Page

**Comment by boonebgorges** [comment]
Sorry for not following up - I may have missed the Basecamp update. The text is now here: https://docs.google.com/document/d/1Sr7E3fL81bq8X7Ji43NXWbBbGbLLLGtR_sIz6sUf0qk/edit#heading=h.hptchnlqopfg

It's complicated to add the 'Edit this text here' link because we should only show that text to someone who has the permission to edit the page. Otherwise it'll be a dead link on a public page. @samradd What do you think of dropping the link in favor of something like: 'If you are the administrator, visit Dashboard > Pages to change this text.' or something like that?

**Comment by samradd** [comment]
If they are going to run into a login page or page that they do not have permissions to access as a non-admin, I don't think it's a big deal if we include the link. We could include clarifying language to make it more obvious that it's for administrators only: "If you are an administrator, edit this text here."

If that's complicated, or an issue for a reason I'm not thinking of, I'm on board with your suggested sentence: 'If you are the administrator, visit Dashboard > Pages > About to modify this text.'

**Comment by boonebgorges** [comment]
Thanks, @samradd. To try to balance simplicity and convenience, here's what I've got:

![screenshot_2018-06-07_16-36-29](https://user-images.githubusercontent.com/246627/41127559-f401478a-6a70-11e8-85c3-ec7cfea88173.png)

So there's text to the effect that you must be an admin, and then there's a link, but it goes to the 'Pages' panel rather than to the specific page. This is technically far easier (otherwise I'd have to create the page, get the ID, then go back and rebuild the content for each one). Let me know if this seems acceptable.

**Comment by samradd** [comment]
That's a reasonable compromise. Approved by me. Thanks!

**Comment by boonebgorges** [comment]
Thank you!

**Comment by bree-z** [comment]
Looks good, thanks!
